// src/components/Header.vue
<template>
  <div class="podlove-header">
    <img class="podlove-header--poster" :src="poster" />
    <div class="podlover-header--info">
      <h1 class="podlove-header--title">{{title}}</h1>
      <div class="podlove-header--subtitle">{{subtitle}}</div>
    </div>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        poster: this.$select('poster'),
        title: this.$select('title'),
        subtitle: this.$select('subtitle')
      }
    }
  }
</script>

// src/components/header/index.jsx
import React from 'react'
import {connect} from 'react-redux'

const Header = ({title, poster, subtitle}) => (
  <div className="podlove-header">
    <img className="podlove-header--poster" src={poster} />
    <div className="podlover-header--info">
      <h1 className="podlove-header--title">{title}</h1>
      <div className="podlove-header--subtitle">{subtitle}</div>
    </div>
  </div>
)

const mapStateToProps = state => ({
  title: state.title,
  subtitle: state.subtitle,
  poster: state.poster
})

export default connect(
  mapStateToProps
)(Header)
