// src/components/player/progress-bar.jsx
import React from 'react'
import {connect} from 'react-redux'

import { player } from '../../actions'

const interpolate = (num = 0) => Math.round(num * 100) / 100

const buffered = (buffer = 0, duration = 1) => {
  const bufferLength = (buffer * 100) / duration

  return {
     width: Math.round(bufferLength) + '%'
  }
}

const ProgressBar = ({playtime, duration, buffer, onMove}) => (
  <div className="podlove-player--progress-bar">
    <input
      className="podlove-player--progress-slider"
      type="range"
      min="0" max={interpolate(duration)} step="0.1"
      value={interpolate(playtime)}
      onChange={onMove}
      data-buffered={buffered(buffer, duration)}
    />
    <span className="podlove-player--progress-buffer" style={buffered(buffer, duration)}></span>
  </div>
)

const mapStateToProps = state => ({
  playtime: state.playtime,
  duration: state.duration,
  buffer: state.buffer
})

const mapDispatchToProps = () => ({
  onMove: event => player.updatePlaytime(event.target.value)
})

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ProgressBar)

// src/components/player/ProgressBar.vue
<template>
  <div class="podlove-player--progress-bar" :class="playstate">
    <input
      type="range"
      min="0" :max="interpolate(duration)" step="0.1"
      :value="interpolate(playtime)"
       v-on:change="onChange"
       v-on:input="onInput"
    />
    <span class="podlove-player--progress-range"></span>
    <span class="podlove-player--progress-buffer" :style="bufferStyle(theme, buffer, duration)"></span>
    <span class="podlove-player--progress-thumb" :style="thumbStyle(theme, thumbPosition)"></span>
    <span class="podlove-player--progress-track" :style="trackStyle(theme, thumbPosition)"></span>
  </div>

</template>

<script>
  import store from 'store'
  import color from 'color'

  const interpolate = (num = 0) => Math.round(num * 100) / 100

  const relativePosition = (current = 0, maximum = 0) =>
    ((current * 100) / maximum) + '%'

  const bufferStyle = (theme, buffer = 0, duration = 1) => ({
    width: relativePosition(buffer, duration),
    'background-color': color(theme.player.progress.bar).fade(0.75)
  })

  const thumbStyle = (theme, position) => ({
      left: position,
      'background-color': theme.player.progress.thumb,
      'border-color': theme.player.progress.border
  })

  const trackStyle = (theme, position) => ({
    width: position,
    'background-color': theme.player.progress.bar
  })

  export default {
    data () {
      return {
        playtime: this.$select('playtime'),
        duration: this.$select('duration'),
        buffer: this.$select('buffer'),
        playstate: this.$select('playstate'),
        theme: this.$select('theme'),
        thumbPosition: 0
      }
    },
    watch: {
      playtime: function (time) {
        this.thumbPosition = relativePosition(time, this.duration)
      }
    },
    methods: {
      onChange (event) {
        store.dispatch(store.actions.updatePlaytime(event.target.value))
      },
      onInput (event) {
        this.thumbPosition = relativePosition(interpolate(event.target.value), this.duration)
      },
      interpolate,
      bufferStyle,
      thumbStyle,
      trackStyle
    }
  }
</script>

<style lang="scss">
  @import 'variables';
  @import 'range-resets';

  .podlove-player--progress-bar {
    width: 100%;
    position: relative;
    height: $padding;
    transition: opacity ($animation-duration / 2), height $animation-duration;
    opacity: 1;

    &.start {
      height: 0;
      opacity: 0;
      overflow: hidden;
    }

    &.idle, &.end {
      .podlove-player--progress-thumb {
        opacity: 0;
      }

      height: $padding * 2;
    }
  }

  .podlove-player--progress-range {
    display: block;
    position: absolute;
    width: 100%;
    left: 0;
    top: 2px;
    height: 2px;
    background-color: rgba($accent-color, 0.25);
  }

  .podlove-player--progress-track {
    display: block;
    position: absolute;
    left: 0;
    top: 2px;
    height: 2px;
  }

  .podlove-player--progress-thumb {
    position: absolute;
    top: 0;
    border: 1px solid;
    margin-top: -5px;
    height: 14px;
    width: 4px;
    pointer-events: none;
  }

  .podlove-player--progress-buffer {
    display: block;
    opacity: 1;
    position: absolute;
    height: 2px;
    top: 2px;
    left: 0;
  }
</style>
